import type { Metadata } from "next";
import { Inter, Balsamiq_Sans } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const balsamiq = Balsamiq_Sans({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-balsamiq",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  login,
  signUp,
  logout,
}: Readonly<{
  children: React.ReactNode;
  login: React.ReactNode;
  signUp: React.ReactNode;
  logout: React.ReactNode;
}>) {
  const isLoggedIn = false;
  return (
    <html lang="en">
      <body className={balsamiq.className}>
        {children}
        {!isLoggedIn && login}
      </body>
    </html>
  );
}
